# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_places', models.IntegerField()),
                ('description_of_hall', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_ticket', models.FloatField()),
                ('tittle', models.CharField(max_length=70)),
                ('time_array', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('question_text', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=2000)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Hall')),
                ('perfomance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Perfomance')),
            ],
        ),
    ]
