# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_auto_20170413_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={'ordering': ['-time_start'], 'verbose_name_plural': 'EventList'},
        ),
        migrations.RemoveField(
            model_name='hall',
            name='number_of_places',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='place',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='place',
            field=models.TextField(default=''),
        ),
    ]
