# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_auto_20170413_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Hall'),
        ),
    ]
