# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_auto_20170413_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='place',
            field=models.TextField(blank=True, default=''),
        ),
    ]
