# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_auto_20170413_1609'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventlist',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
