# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_auto_20170414_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='img',
            field=models.ImageField(null=True, upload_to='theatre//media/post-img/', verbose_name='Path to post-img'),
        ),
    ]
