# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='question_text',
        ),
    ]
