# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_remove_program_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='program',
            name='perfomance',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Perfomance',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
