# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0003_auto_20170412_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_places', models.IntegerField()),
                ('description_of_hall', models.CharField(max_length=100)),
                ('place', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_ticket', models.FloatField()),
                ('tittle', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('data', models.DateField()),
                ('places', models.CharField(max_length=2000)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Hall')),
                ('perfomance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.Perfomance')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
